### ISSUE TITLE
How can I add multiple PDB files support to this project? Can you give some advice or instructions?

### ISSUE THREAD

**Issue by yangalan123** [UoA-eResearch/MolecularVive#2]
Hello, Nick Young! Long time no see. Thanks for your last timely bug fix.  Now, I want to add multiple PDB files support to this project (I mean, input more than one PDB files at once), could you give me some advice or guides? I have tried to analysis the whole project, but it's really tough and I need your help. 

Looking forward to your reply and wish you good life.

**Comment by neon-ninja** [comment]
Hi,

Why would you want to do this? I find the app lags enough as it is with one complicated model, let alone adding more. Anyway, if you did want to do this, I would recommend starting by modifying https://github.com/UoA-eResearch/MolecularVive/blob/master/Assets/Scripts/CustomFileBrowser.cs#L34 so that it concatenates each selected file onto the file_path,file_name variables, probably comma separated. Then, instead of `readMol(file)` (https://github.com/UoA-eResearch/MolecularVive/blob/master/Assets/Scripts/AddAtoms.cs#L200), you'd have to split the string based on comma, then iterate through the resulting array, calling readMol for each file

**Comment by yangalan123** [comment]
Because I used release version before, now I download the whole code and find it can't be directly played in Unity Editor. Why?

**Comment by neon-ninja** [comment]
You'll need to play the launcher scene, and select options (mainly, an example PDB file) before the main scene will work

**Comment by yangalan123** [comment]
Emmm....I do play the LoadScreeen Scene, but it just doesn't work. 
"OpenVR initialized."->"OpenVR shutdown" (happened so quickly)

**Comment by neon-ninja** [comment]
Is your vive connected and is steamvr running

**Comment by yangalan123** [comment]
Sure.

**Comment by neon-ninja** [comment]
Does the play button stay blue or does it drop you out of play mode?

**Comment by neon-ninja** [comment]
You need to select the options with keyboard and mouse not within the vive

**Comment by yangalan123** [comment]
The play button stay blue.....wait? I need to select the options with keyboard and mouse not within the vive? Not like what I was doing in release version?

**Comment by neon-ninja** [comment]
When you first start up the release version you have to select your desired model with the keyboard and mouse too

**Comment by yangalan123** [comment]
.......Oh.....I forget it........Sorry for bothering.

**Comment by yangalan123** [comment]
Well, I have changed some part of the code, and I did see two models in Unity Editor, but when I tried to build it, I found that the exported file can only read the file and show the background in Vive, but I couldn't see any model. I try to use X86_64/X86 to build and I even change the version of Unity, but it simple couldn't work. Then I tried to download the files in master branch, but it couldn't display the model after build. 
Are there any extra steps I should take to build it?

**Comment by neon-ninja** [comment]
Yes. Run the batch script called `post_build.bat`. It's a one liner that does `copy Assets\Plugins\formats_common.obf Build\MolecularVive_Data\Plugins` (that's assuming you're building into a folder called Build). The obf file needs to be housed with the dll but Unity won't include it because it doesn't recognise obf format.
